#!/bin/bash

GO_PATH=$(pwd)
GO_BIN=$GO_PATH/bin

export GOPATH=$GO_PATH
export GOBIN=$GO_BIN

go get github.com/Mellanox/rdmamap
go get github.com/Mellanox/sriovnet
go get github.com/docker/docker/api/types
go get github.com/spf13/cobra
go get github.com/docker/docker/client

go get github.com/vishvananda/netlink
go get github.com/docker/docker/client

export GIT_COMMIT=$(git rev-list -1 HEAD)
CGO_ENABLED=0 GOOS=linux go build -a -ldflags "-X main.GitCommitId=$GIT_COMMIT -extldflags "-static"" -o bin/k8sdo k8sdo
